#!/usr/bin/env bash
set -ue

# Runfile script

USAGE="Usage: run -e|vim|mvim|install|uninstall|etc..."

if (( $# )); then
    runcmd="$1"
    shift
else
    echo "$USAGE"
    exit 1
fi


# Add run commands as switch cases below. Do not make edits
# outside of case blocks. Note: Optional args are available
# as "${@}". If used, consider the first line in the block
# as a usage statement.


function __conda_check {
    if [[ "${CONDA_DEFAULT_ENV+x}" ]]; then
        if [[ "$CONDA_DEFAULT_ENV" != flymodel ]]; then
            echo "Wrong environment ($CONDA_DEFAULT_ENV). Please switch to the"
            echo "'flymodel' environment with 'source activate flymodel'."
            exit 1
        fi
    else
        echo "Please run 'source activate flymodel' first."
        exit 2
    fi
}

case "$runcmd" in

vim)
    if [[ -f Session.vim ]]; then
        vim -S Session.vim
    else
        vim flymodel
    fi
    ;;

mvim)
    if [[ -f Session.vim ]]; then
        mvim -S Session.vim &>/dev/null
    else
        mvim flymodel &>/dev/null
    fi
    ;;

install) pip install --no-deps -e "$HOME/code/flymodel" ;;

uninstall) pip uninstall -y flymodel ;;

tmux) tmux new-session -A -s flymodel ;;

exportenv)
    __conda_check
    conda env export -f environment.yml && \
        git add environment.yml && \
        git diff --cached
    ;;

ipython)
    __conda_check
    ipython --profile=flymodel
    ;;

cluster)
    __conda_check
    ipcluster start --profile=flymodel
    ;;

notebook)
    __conda_check
    ipcluster start --profile=flymodel
    jupyter notebook --notebook-dir="$HOME/projects/flymodel/notebooks" &
    ;;

killnb) pkill -f jupyter ;;

finder) open . -a finder ;;

tests) py.test -q tests ;;

*)
    echo $USAGE
    exit 1
    ;;

esac
